version: "3.8"
services:
  dev-db:
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: army
    networks:
      - armydb
networks:
  armydb:
